// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/admin/auth_admin_service.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	InviteToken   string                 `protobuf:"bytes,3,opt,name=invite_token,json=inviteToken,proto3" json:"invite_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetInviteToken() string {
	if x != nil {
		return x.InviteToken
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateInviteTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteTokenRequest) Reset() {
	*x = CreateInviteTokenRequest{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteTokenRequest) ProtoMessage() {}

func (x *CreateInviteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateInviteTokenRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateInviteTokenRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type CreateInviteTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteTokenResponse) Reset() {
	*x = CreateInviteTokenResponse{}
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteTokenResponse) ProtoMessage() {}

func (x *CreateInviteTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_auth_admin_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateInviteTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_auth_admin_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateInviteTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_v1_admin_auth_admin_service_proto protoreflect.FileDescriptor

const file_v1_admin_auth_admin_service_proto_rawDesc = "" +
	"\n" +
	"!v1/admin/auth_admin_service.proto\x126github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin\"f\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12!\n" +
	"\finvite_token\x18\x03 \x01(\tR\vinviteToken\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"D\n" +
	"\x15ValidateTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x18CreateInviteTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"1\n" +
	"\x19CreateInviteTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xf9\a\n" +
	"\x10AuthAdminService\x12\x9d\x01\n" +
	"\bRegister\x12G.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RegisterRequest\x1aH.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RegisterResponse\x12\x94\x01\n" +
	"\x05Login\x12D.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LoginRequest\x1aE.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LoginResponse\x12\xac\x01\n" +
	"\rValidateToken\x12L.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.ValidateTokenRequest\x1aM.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.ValidateTokenResponse\x12\xa9\x01\n" +
	"\fRefreshToken\x12K.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RefreshTokenRequest\x1aL.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RefreshTokenResponse\x12\x97\x01\n" +
	"\x06Logout\x12E.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LogoutRequest\x1aF.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LogoutResponse\x12\xb8\x01\n" +
	"\x11CreateInviteToken\x12P.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.CreateInviteTokenRequest\x1aQ.github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.CreateInviteTokenResponseB>Z<github.com/martketplace-vkr/auth/pkg/api/grpc/v1/admin;adminb\x06proto3"

var (
	file_v1_admin_auth_admin_service_proto_rawDescOnce sync.Once
	file_v1_admin_auth_admin_service_proto_rawDescData []byte
)

func file_v1_admin_auth_admin_service_proto_rawDescGZIP() []byte {
	file_v1_admin_auth_admin_service_proto_rawDescOnce.Do(func() {
		file_v1_admin_auth_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_auth_admin_service_proto_rawDesc), len(file_v1_admin_auth_admin_service_proto_rawDesc)))
	})
	return file_v1_admin_auth_admin_service_proto_rawDescData
}

var file_v1_admin_auth_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_admin_auth_admin_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),           // 0: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RegisterRequest
	(*RegisterResponse)(nil),          // 1: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RegisterResponse
	(*LoginRequest)(nil),              // 2: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LoginRequest
	(*LoginResponse)(nil),             // 3: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LoginResponse
	(*ValidateTokenRequest)(nil),      // 4: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),     // 5: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.ValidateTokenResponse
	(*RefreshTokenRequest)(nil),       // 6: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),      // 7: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RefreshTokenResponse
	(*LogoutRequest)(nil),             // 8: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LogoutRequest
	(*LogoutResponse)(nil),            // 9: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LogoutResponse
	(*CreateInviteTokenRequest)(nil),  // 10: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.CreateInviteTokenRequest
	(*CreateInviteTokenResponse)(nil), // 11: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.CreateInviteTokenResponse
}
var file_v1_admin_auth_admin_service_proto_depIdxs = []int32{
	0,  // 0: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.Register:input_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RegisterRequest
	2,  // 1: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.Login:input_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LoginRequest
	4,  // 2: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.ValidateToken:input_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.ValidateTokenRequest
	6,  // 3: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.RefreshToken:input_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RefreshTokenRequest
	8,  // 4: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.Logout:input_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LogoutRequest
	10, // 5: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.CreateInviteToken:input_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.CreateInviteTokenRequest
	1,  // 6: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.Register:output_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RegisterResponse
	3,  // 7: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.Login:output_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LoginResponse
	5,  // 8: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.ValidateToken:output_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.ValidateTokenResponse
	7,  // 9: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.RefreshToken:output_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.RefreshTokenResponse
	9,  // 10: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.Logout:output_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.LogoutResponse
	11, // 11: github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.AuthAdminService.CreateInviteToken:output_type -> github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin.CreateInviteTokenResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_admin_auth_admin_service_proto_init() }
func file_v1_admin_auth_admin_service_proto_init() {
	if File_v1_admin_auth_admin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_auth_admin_service_proto_rawDesc), len(file_v1_admin_auth_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_auth_admin_service_proto_goTypes,
		DependencyIndexes: file_v1_admin_auth_admin_service_proto_depIdxs,
		MessageInfos:      file_v1_admin_auth_admin_service_proto_msgTypes,
	}.Build()
	File_v1_admin_auth_admin_service_proto = out.File
	file_v1_admin_auth_admin_service_proto_goTypes = nil
	file_v1_admin_auth_admin_service_proto_depIdxs = nil
}
