syntax = "proto3";

package github.com.martketplace.vkr.auth.pkg.api.grpc.v1.admin;

option go_package = "github.com/martketplace-vkr/auth/pkg/api/grpc/v1/admin;admin";

service AuthAdminService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc CreateInviteToken(CreateInviteTokenRequest) returns (CreateInviteTokenResponse);
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string invite_token = 3;
}

message RegisterResponse {
  int64 user_id = 1;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  int64 user_id = 1;
  string role = 2;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  bool success = 1;
}

message CreateInviteTokenRequest {
  int64 user_id = 1;
  int64 role_id = 2;
}

message CreateInviteTokenResponse {
  string token = 1;
}
